//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PennyApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feature
    {
        public int Id { get; set; }
        public Nullable<int> Moving_Avg { get; set; }
        public Nullable<int> Moving_Avg_Filter { get; set; }
        public Nullable<int> Volume { get; set; }
        public Nullable<int> Volume_Filter { get; set; }
        public Nullable<int> Day_High { get; set; }
        public Nullable<int> Performance { get; set; }
        public Nullable<int> Consecutive_High { get; set; }
        public Nullable<int> Consecutive_Low { get; set; }
        public Nullable<int> Consecutive_Low_Filter { get; set; }
        public Nullable<int> RSI { get; set; }
        public Nullable<int> RSIfrom { get; set; }
        public Nullable<int> RSIto { get; set; }
        public Nullable<int> Stochastics { get; set; }
        public Nullable<int> StochasticsFrom { get; set; }
        public Nullable<int> StochasticsTo { get; set; }
        public Nullable<int> MACD_Hist { get; set; }
        public Nullable<int> MACD_HistFrom { get; set; }
        public Nullable<int> MACD_HistTo { get; set; }
        public Nullable<int> Upper_BBand { get; set; }
        public Nullable<int> Upper_BBandFrom { get; set; }
        public Nullable<int> Upper_BBandTo { get; set; }
        public int Lower_BBand { get; set; }
        public Nullable<int> Lower_BBandFrom { get; set; }
        public Nullable<int> Lower_BBandTo { get; set; }
    }
}
