//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PennyApp.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PennyAppEntities : DbContext
    {
        public PennyAppEntities()
            : base("name=PennyAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Filter> Filters { get; set; }
        public virtual DbSet<ReduceBy> ReduceBies { get; set; }
        public virtual DbSet<ReportPeriod> ReportPeriods { get; set; }
        public virtual DbSet<Simulation> Simulations { get; set; }
        public virtual DbSet<StopOption> StopOptions { get; set; }
        public virtual DbSet<Feature> Features { get; set; }
        public virtual DbSet<Trail> Trails { get; set; }
        public virtual DbSet<Trade> Trades { get; set; }

        public System.Data.Entity.DbSet<PennyApp.Models.SimulationViewModel> SimulationViewModels { get; set; }
    }
}
