//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PennyApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Video2 { get; set; }
        public int QuestionType { get; set; }
        public string Audio1 { get; set; }
        public string Audio2 { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string Image4 { get; set; }
        public string Image5 { get; set; }
        public string Text1 { get; set; }
        public string Text10 { get; set; }
        public string Text2 { get; set; }
        public string Text3 { get; set; }
        public string Text4 { get; set; }
        public string Text5 { get; set; }
        public string Text6 { get; set; }
        public string Text7 { get; set; }
        public string Text8 { get; set; }
        public string Text9 { get; set; }
        public Nullable<decimal> Transition1 { get; set; }
        public Nullable<decimal> Transition10 { get; set; }
        public Nullable<decimal> Transition2 { get; set; }
        public Nullable<decimal> Transition3 { get; set; }
        public Nullable<decimal> Transition4 { get; set; }
        public Nullable<decimal> Transition5 { get; set; }
        public Nullable<decimal> Transition6 { get; set; }
        public Nullable<decimal> Transition7 { get; set; }
        public Nullable<decimal> Transition8 { get; set; }
        public Nullable<decimal> Transition9 { get; set; }
        public string Video1 { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public bool ContainsAdultContent { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
