//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PennyApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StopOption
    {
        public int Id { get; set; }
        public Nullable<int> Stop_Option { get; set; }
        public Nullable<int> Stop_Option_Status { get; set; }
        public Nullable<int> Stop_Option_Value { get; set; }
        public Nullable<int> Trail_Stop { get; set; }
        public Nullable<int> Trail_Stop_Status { get; set; }
        public Nullable<int> Trail_Stop_Value { get; set; }
        public Nullable<int> Price_On { get; set; }
        public Nullable<int> Price_Status { get; set; }
        public Nullable<int> Price_ValueFrom { get; set; }
        public Nullable<int> Price_ValueTo { get; set; }
        public Nullable<int> Valume_On { get; set; }
        public Nullable<int> Valume_Status { get; set; }
        public Nullable<int> Avg_Volume_On { get; set; }
        public Nullable<int> Avg_Volume_Status { get; set; }
        public Nullable<int> Avg_Volume_Value1 { get; set; }
        public Nullable<int> Avg_Volume_Value2 { get; set; }
    }
}
