//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PennyApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trail
    {
        public int Id { get; set; }
        public string TickerName { get; set; }
        public int RunnigStatus { get; set; }
        public Nullable<double> Realized { get; set; }
        public Nullable<double> Unrealized { get; set; }
        public Nullable<int> TotalShares { get; set; }
        public Nullable<int> Exit1 { get; set; }
        public Nullable<int> Exit2 { get; set; }
        public Nullable<int> Exit3 { get; set; }
        public Nullable<int> Exit4 { get; set; }
        public Nullable<int> Exit5 { get; set; }
        public Nullable<int> Exit6 { get; set; }
        public Nullable<int> Exit7 { get; set; }
        public Nullable<int> Exit8 { get; set; }
        public Nullable<int> Exit9 { get; set; }
        public Nullable<int> Entry_price { get; set; }
        public Nullable<int> Amout { get; set; }
        public Nullable<double> Price_Now { get; set; }
    }
}
